version: '2'
checks:
  duplication:
    enabled: true
  eslint:
    enabled: true
    config:
      extends: eslint:recommended
      parserOptions:
        ecmaVersion: 2021
      env:
        browser: true
        es6: true
      rules:
        semi:
          - error
          - always
        quotes:
          - error
          - single
